apiVersion: v1
kind: Service
metadata:
  name: alertmanager  # ชื่อของ Service ที่ใช้
  namespace: prod  # แทนด้วย namespace ที่คุณติดตั้ง Alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
spec:
  type: NodePort  # กำหนดประเภทเป็น NodePort เพื่อให้เข้าถึงจากภายนอกได้
  ports:
    - port: 9093            # พอร์ตที่จะใช้ในการเข้าถึงจากภายนอก
      targetPort: 9093      # พอร์ตภายในคอนเทนเนอร์ของ Alertmanager (ปกติคือ 9093)
      nodePort: 32002       # พอร์ตที่เปิดบน Node สำหรับการเข้าถึงจากภายนอก (ต้องอยู่ในช่วง 30000-32767)
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
