apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vproapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vproapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
