apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vprodb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vprodb
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
