apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vproapp-to-vprocache
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: vpromc
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vproapp
    ports:
    - protocol: TCP
      port: 11211
