apiVersion: batch/v1
kind: Job
metadata:
  name: delete-pod
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  template:
    spec:
      containers:
      - name: delete-pod
        image: bitnami/kubectl:latest
        command:
        - "/bin/sh"
        - "-c"
        - "kubectl delete pod secret-env-pod --namespace prod || true"
      restartPolicy: Never
