apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: db-pass
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "username"
      - name: RABBITMQ_DEFAULT_PASS
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: rmq-pass
            optional: false # same as default; "mysecret" must exist
                            # and include a key named "password"
  restartPolicy: Never

