apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prod  # แทนด้วย namespace ที่คุณติดตั้ง Grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
spec:
  type: NodePort  # กำหนดประเภทเป็น NodePort เพื่อให้เข้าถึงจากภายนอกได้
  ports:
    - port: 80               # พอร์ตที่จะใช้ในการเข้าถึงจากภายนอก
      targetPort: 3000       # พอร์ตภายในคอนเทนเนอร์ของ Grafana (ปกติคือ 3000)
      nodePort: 32000        # พอร์ตที่เปิดบน Node สำหรับการเข้าถึงจากภายนอก (ต้องอยู่ในช่วง 30000-32767)
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-operator
