apiVersion: v1
kind: Service
metadata:
  name: prometheus  # ชื่อของ Service
  namespace: prod   # เปลี่ยนให้ตรงกับ namespace ที่ Prometheus ถูกติดตั้ง
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-operator-kube-p-prometheus
spec:
  type: NodePort  # กำหนดประเภทเป็น NodePort เพื่อให้เข้าถึงจากภายนอกได้
  ports:
    - port: 9090              # พอร์ตที่ใช้ในการเข้าถึง Prometheus
      targetPort: 9090        # พอร์ตภายในคอนเทนเนอร์ของ Prometheus (ปกติคือ 9090)
      nodePort: 32001         # พอร์ตที่เปิดบน Node สำหรับการเข้าถึงจากภายนอก (ต้องอยู่ในช่วง 30000-32767)
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-operator-kube-p-prometheus
